// Builds public/icons.svg, an SVG sprite of the Lucide icons the UI uses.
// Run with `npm run icons` after changing the list below.
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";

const ICONS = [
  "arrow-left",
  "audio-lines",
  "captions",
  "check",
  "circle-dot",
  "circle-stop",
  "copy",
  "crown",
  "download",
  "ellipsis-vertical",
  "file",
  "hand",
  "info",
  "keyboard",
  "link",
  "lock",
  "lock-open",
  "maximize",
  "message-square",
  "mic",
  "mic-off",
  "minimize",
  "monitor",
  "monitor-up",
  "monitor-x",
  "paperclip",
  "phone-off",
  "pin",
  "pin-off",
  "send",
  "settings",
  "signal",
  "smile",
  "sparkles",
  "switch-camera",
  "triangle-alert",
  "user-plus",
  "user-x",
  "users",
  "video",
  "video-off",
  "volume-2",
  "wifi-off",
  "x",
];

const STYLE =
  'fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"';

const require = createRequire(import.meta.url);
const dir = path.join(path.dirname(require.resolve("lucide-static/package.json")), "icons");
const { version } = require("lucide-static/package.json");

const symbols = ICONS.map((name) => {
  const svg = readFileSync(path.join(dir, `${name}.svg`), "utf8");
  const body = svg
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>\s*$/, "")
    .replace(/\s*\n\s*/g, "");
  // Attributes on the root <svg> don't reach symbols used via <use>, so
  // each symbol carries its own.
  return `  <symbol id="${name}" viewBox="0 0 24 24" ${STYLE}>${body}</symbol>`;
});

const sprite = `<!-- Lucide icons v${version} (ISC License, https://lucide.dev). Generated by scripts/build-icons.mjs. -->
<svg xmlns="http://www.w3.org/2000/svg">
${symbols.join("\n")}
</svg>
`;
writeFileSync(new URL("../public/icons.svg", import.meta.url), sprite);
console.log(`Wrote ${ICONS.length} icons to public/icons.svg`);
